### ISSUE TITLE
Instagram.js 

### ISSUE THREAD

**Issue by hdrdavies** [kat4/instaground#19]
On line 19:

https://github.com/kat4/instaground/blob/gh-pages/instagram.js#L19
## Would you consider using more typical syntax to make this code a little more readable? Like you've done from line 22. 

When I spoke to you guys in a very civil manner, it appears you didn't know what was going on in line 60:

https://github.com/kat4/instaground/blob/gh-pages/instagram.js#L60

...where you generate a large number on the end of the URL. Would you consider writing code that you can understand?

**Comment by mantagen** [comment]
Thanks,
Will consider this...
